# Generated by Django 5.2.5 on 2025-08-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="MediaContentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ManualConnector",
            fields=[
                (
                    "connector_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="connectors.connector",
                    ),
                ),
                ("content_data", models.TextField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("connectors.connector",),
        ),
        migrations.CreateModel(
            name="ScraperConnector",
            fields=[
                (
                    "connector_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="connectors.connector",
                    ),
                ),
                ("base_url", models.URLField(help_text="Main page to scrape from")),
                (
                    "image_selector",
                    models.CharField(
                        help_text="CSS selector for the image element", max_length=255
                    ),
                ),
                (
                    "title_selector",
                    models.CharField(
                        help_text="CSS selector for the title element", max_length=255
                    ),
                ),
                (
                    "description_selector",
                    models.CharField(
                        blank=True,
                        help_text="Optional CSS selector for description",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("connectors.connector",),
        ),
        migrations.AddField(
            model_name="connector",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connector",
                to="connectors.mediacontentsource",
            ),
        ),
        migrations.CreateModel(
            name="ManualConnectorImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media_content_images/")),
                (
                    "manual_connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="connectors.manualconnector",
                    ),
                ),
            ],
        ),
    ]
