# Generated by Django 5.2.5 on 2025-08-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connector",
            name="source",
        ),
        migrations.AddField(
            model_name="connector",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
