# Generated by Django 5.2.5 on 2025-08-10 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0002_remove_connector_source_connector_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrappedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scraped_data", models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_caption", models.TextField(blank=True, default="")),
                ("caption", models.TextField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "post_identifier",
                    models.CharField(blank=True, max_length=300, unique=True),
                ),
                (
                    "social_media",
                    models.CharField(
                        choices=[("facebook", "Facebook"), ("instagram", "Instagram")],
                        max_length=50,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("post", "Post"), ("reel", "Reel")],
                        default="post",
                        max_length=50,
                    ),
                ),
                (
                    "sound_track",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MediaContentSource",
        ),
        migrations.RenameField(
            model_name="scraperconnector",
            old_name="created_at",
            new_name="last_ran",
        ),
        migrations.AddField(
            model_name="scrappeditem",
            name="connector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrapped_items",
                to="connectors.scraperconnector",
            ),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="scrapped_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_posts",
                to="connectors.scrappeditem",
            ),
        ),
    ]
