# Generated by Django 5.2.5 on 2025-08-17 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_scrappeditem_socialpost_delete_mediacontentsource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='post_identifier',
        ),
        migrations.AlterField(
            model_name='connector',
            name='name',
            field=models.CharField(default='', help_text='Name of the connector', max_length=255),
        ),
        migrations.AlterField(
            model_name='manualconnector',
            name='content_data',
            field=models.TextField(help_text='Content data for the manual connector'),
        ),
        migrations.AlterField(
            model_name='manualconnectorimage',
            name='image',
            field=models.ImageField(help_text='Image file for the manual connector', upload_to='media_content_images/'),
        ),
        migrations.AlterField(
            model_name='manualconnectorimage',
            name='manual_connector',
            field=models.ForeignKey(help_text='Manual connector that this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='connectors.manualconnector'),
        ),
        migrations.AlterField(
            model_name='scrappeditem',
            name='connector',
            field=models.ForeignKey(help_text='Connector that scraped this item', on_delete=django.db.models.deletion.CASCADE, related_name='scrapped_items', to='connectors.scraperconnector'),
        ),
        migrations.AlterField(
            model_name='scrappeditem',
            name='scraped_data',
            field=models.JSONField(default={}, help_text="Data scraped from the connector's source"),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='ai_caption',
            field=models.TextField(blank=True, default='', help_text='Caption generated by AI, if applicable'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='caption',
            field=models.TextField(help_text='Caption for the post'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('reel', 'Reel')], default='post', help_text='Type of content for the post', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the post was created'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='scrapped_item',
            field=models.ForeignKey(help_text='The scrapped item that this post is based on', on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='connectors.scrappeditem'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='social_media',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], help_text='Social media platform for the post', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='sound_track',
            field=models.CharField(blank=True, default='', help_text='Sound track used for the post, if applicable', max_length=255),
        ),
    ]
