# Generated by Django 5.2.5 on 2025-08-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MediaContentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MediaContentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media_content_images/")),
                (
                    "media_content_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="scheduler.mediacontent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mediacontent",
            name="source",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_contents",
                to="scheduler.mediacontentsource",
            ),
        ),
        migrations.CreateModel(
            name="SocialSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_media",
                    models.CharField(
                        choices=[("instagram", "Instagram"), ("facebook", "Facebook")],
                        max_length=100,
                    ),
                ),
                (
                    "social_media_channel",
                    models.CharField(
                        choices=[("reel", "Reel"), ("post", "Post")], max_length=100
                    ),
                ),
                ("api_key", models.CharField(max_length=300)),
                ("social_media_id", models.CharField(max_length=100)),
                ("schedule", models.CharField(default="*/15 * * * *", max_length=100)),
                ("default_caption", models.CharField(blank=True, max_length=300)),
                ("use_ai_caption", models.BooleanField(default=True)),
                ("hashtags", models.JSONField(default=list)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("skip", models.BooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="connectors.connector",
                    ),
                ),
            ],
        ),
    ]
