# Generated by Django 5.2.5 on 2025-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_media", models.CharField(max_length=100)),
                ("social_media_channel", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=300)),
                ("social_media_id", models.CharField(max_length=100)),
                ("schedule", models.CharField(max_length=100)),
            ],
        ),
    ]
