# Generated by Django 5.2.5 on 2025-08-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialschedule",
            name="skip",
        ),
        migrations.AddField(
            model_name="socialschedule",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
