# Generated by Django 5.2.5 on 2025-08-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialschedule",
            name="source_url",
            field=models.URLField(default=""),
        ),
    ]
