# Generated by Django 5.2.5 on 2025-08-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_socialschedule_source_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="socialschedule",
            name="schedule",
            field=models.CharField(default="*/15 * * * *", max_length=100),
        ),
        migrations.CreateModel(
            name="MediaContentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media_content_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "media_content_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="scheduler.mediacontent",
                    ),
                ),
            ],
        ),
    ]
