# Generated by Django 5.2.5 on 2025-08-17 20:52

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_remove_socialpost_post_identifier_and_more'),
        ('scheduler', '0002_remove_socialschedule_skip_socialschedule_active'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialschedule',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the schedule active?'),
        ),
        migrations.AlterField(
            model_name='socialschedule',
            name='api_key',
            field=models.CharField(help_text='API Key for the social media platform', max_length=300),
        ),
        migrations.AlterField(
            model_name='socialschedule',
            name='default_caption',
            field=models.CharField(blank=True, help_text='Default caption for the post.', max_length=300),
        ),
        migrations.RemoveField(
            model_name='socialschedule',
            name='hashtags',
        ),
        migrations.AlterField(
            model_name='socialschedule',
            name='last_run',
            field=models.DateTimeField(blank=True, help_text='Last time the schedule was run.', null=True),
        ),
        migrations.AlterField(
            model_name='socialschedule',
            name='schedule',
            field=models.CharField(default='*/15 * * * *', help_text='Cron schedule expression', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialschedule',
            name='social_media',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook')], help_text='Social Media Platform', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialschedule',
            name='social_media_channel',
            field=models.CharField(choices=[('reel', 'Reel'), ('post', 'Post')], help_text='Channel for the social media. Example: Post, Reel, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialschedule',
            name='social_media_id',
            field=models.CharField(help_text='Social Media ID for the account', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialschedule',
            name='source',
            field=models.ForeignKey(blank=True, default='', help_text='Source of the content', null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectors.connector'),
        ),
        migrations.AlterField(
            model_name='socialschedule',
            name='use_ai_caption',
            field=models.BooleanField(default=True, help_text='Use AI to generate caption for the post.', verbose_name='Use AI Caption'),
        ),
        migrations.AddField(
            model_name='socialschedule',
            name='hashtags',
            field=taggit.managers.TaggableManager(blank=True, help_text='List of hashtags to be used in the post.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
