# Generated by Django 5.2.5 on 2025-08-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_mediacontent_alter_socialschedule_schedule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediacontent",
            name="title",
        ),
        migrations.RemoveField(
            model_name="mediacontentimage",
            name="caption",
        ),
    ]
