# Generated by Django 5.2.5 on 2025-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_remove_mediacontent_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialschedule",
            name="last_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
