# Generated by Django 5.2.5 on 2025-08-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_socialschedule_last_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialschedule",
            name="social_media",
            field=models.CharField(
                choices=[("instagram", "Instagram"), ("facebook", "Facebook")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="socialschedule",
            name="social_media_channel",
            field=models.CharField(
                choices=[("reel", "Reel"), ("post", "Post")], max_length=100
            ),
        ),
    ]
