# Generated by Django 5.2.5 on 2025-08-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_alter_socialschedule_social_media_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaContentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="socialschedule",
            name="source_url",
        ),
        migrations.AddField(
            model_name="mediacontent",
            name="source",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_contents",
                to="scheduler.mediacontentsource",
            ),
        ),
        migrations.AddField(
            model_name="socialschedule",
            name="source",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scheduler.mediacontentsource",
            ),
        ),
    ]
