# Generated by Django 5.2.5 on 2025-08-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduler",
            "0007_mediacontentsource_remove_socialschedule_source_url_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediacontent",
            old_name="body",
            new_name="content_data",
        ),
    ]
