# Generated by Django 5.2.5 on 2025-08-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0008_rename_body_mediacontent_content_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialschedule",
            name="default_caption",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
