# Generated by Django 5.2.5 on 2025-08-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0009_socialschedule_default_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialschedule",
            name="skip",
            field=models.BooleanField(default=False),
        ),
    ]
