# Generated by Django 5.2.5 on 2025-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0010_socialschedule_skip"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialschedule",
            name="hashtags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="socialschedule",
            name="use_ai_caption",
            field=models.BooleanField(default=True),
        ),
    ]
